/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Web3DomainsV2 } from "./Web3DomainsV2";

export { Web3DomainsV2__factory } from "./factories/Web3DomainsV2__factory";
